FROM python:3.12-slim

WORKDIR /app

COPY runtime_requirements.txt /tmp/runtime_requirements.txt
RUN pip install --no-cache-dir -r /tmp/runtime_requirements.txt

COPY backend/app /app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0","--port", "8000"]